export const sagaActions = {
  FETCH_SHOPPING_ITEMS: 'FETCH_SHOPPING_ITEMS',
  ADD_SHOPPING_ITEM: 'ADD_SHOPPING_ITEM',
  DELETE_SHOPPING_ITEM: 'DELETE_SHOPPING_ITEM',
  EDIT_SHOPPING_ITEM: 'EDIT_SHOPPING_ITEM',
}
